import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import "@mantine/core/styles.css";
import "mantine-datatable/styles.layer.css";

import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import {
  ClerkProvider,
  SignIn,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import RootShell from "./shell";
import Welcome from "@/components/welcome";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <ColorSchemeScript />
        </head>
        <body>
          <SignedOut>
            <div
              style={{
                display: "flex",
                justifyContent: "center",
                alignItems: "center",
                minHeight: "100vh",
              }}
            >
              <SignIn routing="hash" />
            </div>
          </SignedOut>
          <SignedIn>
            <MantineProvider
              theme={{
                fontFamily: poppins.style.fontFamily,
              }}
            >
              <RootShell>
                <div style={{ position: "fixed", top: 8, right: 8 }}>
                  <UserButton />
                </div>
                <Welcome />
                {children}
              </RootShell>
            </MantineProvider>
          </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  );
}
