const PRIMARY_COLOR = '#38598b';
const SECONDARY_COLOR = '#113F67';
const TEXT_COLOR = '#3f4549';
const BUTTON_BASE_COLOR = '#5177b0';
const PROGRESS_BAR_COLOR = '#9bbb59';

export { PRIMARY_COLOR, SECONDARY_COLOR, TEXT_COLOR, BUTTON_BASE_COLOR, PROGRESS_BAR_COLOR };
